import * as FlagSvgs from "country-flag-icons/string/3x2";

const BANDERAS_SVG = {
    MEX: FlagSvgs.MX,
    RSA: FlagSvgs.ZA,
    KOR: FlagSvgs.KR,
    CZE: FlagSvgs.CZ,
    CAN: FlagSvgs.CA,
    BIH: FlagSvgs.BA,
    QAT: FlagSvgs.QA,
    SUI: FlagSvgs.CH,
    BRA: FlagSvgs.BR,
    MAR: FlagSvgs.MA,
    HAI: FlagSvgs.HT,
    SCO: FlagSvgs.GB_SCT,
    USA: FlagSvgs.US,
    TUR: FlagSvgs.TR,
    AUS: FlagSvgs.AU,
    PAR: FlagSvgs.PY,
    GER: FlagSvgs.DE,
    CUW: FlagSvgs.CW,
    CIV: FlagSvgs.CI,
    ECU: FlagSvgs.EC,
    NED: FlagSvgs.NL,
    JPN: FlagSvgs.JP,
    SWE: FlagSvgs.SE,
    TUN: FlagSvgs.TN,
    BEL: FlagSvgs.BE,
    EGY: FlagSvgs.EG,
    IRN: FlagSvgs.IR,
    NZL: FlagSvgs.NZ,
    ESP: FlagSvgs.ES,
    CPV: FlagSvgs.CV,
    KSA: FlagSvgs.SA,
    URU: FlagSvgs.UY,
    FRA: FlagSvgs.FR,
    SEN: FlagSvgs.SN,
    IRQ: FlagSvgs.IQ,
    NOR: FlagSvgs.NO,
    ARG: FlagSvgs.AR,
    ALG: FlagSvgs.DZ,
    AUT: FlagSvgs.AT,
    JOR: FlagSvgs.JO,
    POR: FlagSvgs.PT,
    COD: FlagSvgs.CD,
    UZB: FlagSvgs.UZ,
    COL: FlagSvgs.CO,
    ENG: FlagSvgs.GB_ENG,
    CRO: FlagSvgs.HR,
    GHA: FlagSvgs.GH,
    PAN: FlagSvgs.PA,
};

export const obtenerBanderaSvg = (codigo) => BANDERAS_SVG[codigo] ?? null;
export default BANDERAS_SVG;
